#if !canImport(ObjectiveC)
import XCTest

extension AppTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AppTests = [
        ("testHelloWorld", testHelloWorld),
    ]
}

extension DailyStatisticsJobTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DailyStatisticsJobTests = [
        ("testCreatesDailyCount", testCreatesDailyCount),
    ]
}

extension HealthcheckTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HealthcheckTests = [
        ("testJobsAreHealthy", testJobsAreHealthy),
        ("testJobsAreNotRunning", testJobsAreNotRunning),
    ]
}

extension StatisticsControllerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StatisticsControllerTests = [
        ("testBuildCounts", testBuildCounts),
        ("testBuildStatus", testBuildStatus),
        ("testBuildTimes", testBuildTimes),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AppTests.__allTests__AppTests),
        testCase(DailyStatisticsJobTests.__allTests__DailyStatisticsJobTests),
        testCase(HealthcheckTests.__allTests__HealthcheckTests),
        testCase(StatisticsControllerTests.__allTests__StatisticsControllerTests),
    ]
}
#endif
