//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: src/main/protobuf/command_server.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import GRPC
import NIO
import NIOHTTP1
import SwiftProtobuf


/// Usage: instantiate CommandServer_CommandServerServiceClient, then call methods of this protocol to make API calls.
public protocol CommandServer_CommandServerService {
  func run(_ request: CommandServer_RunRequest, callOptions: CallOptions?, handler: @escaping (CommandServer_RunResponse) -> Void) -> ServerStreamingCall<CommandServer_RunRequest, CommandServer_RunResponse>
  func cancel(_ request: CommandServer_CancelRequest, callOptions: CallOptions?) -> UnaryCall<CommandServer_CancelRequest, CommandServer_CancelResponse>
  func ping(_ request: CommandServer_PingRequest, callOptions: CallOptions?) -> UnaryCall<CommandServer_PingRequest, CommandServer_PingResponse>
}

public final class CommandServer_CommandServerServiceClient: GRPCClient, CommandServer_CommandServerService {
  public let connection: ClientConnection
  public var defaultCallOptions: CallOptions

  /// Creates a client for the command_server.CommandServer service.
  ///
  /// - Parameters:
  ///   - connection: `ClientConnection` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  public init(connection: ClientConnection, defaultCallOptions: CallOptions = CallOptions()) {
    self.connection = connection
    self.defaultCallOptions = defaultCallOptions
  }

  /// Asynchronous server-streaming call to Run.
  ///
  /// - Parameters:
  ///   - request: Request to send to Run.
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ServerStreamingCall` with futures for the metadata and status.
  public func run(_ request: CommandServer_RunRequest, callOptions: CallOptions? = nil, handler: @escaping (CommandServer_RunResponse) -> Void) -> ServerStreamingCall<CommandServer_RunRequest, CommandServer_RunResponse> {
    return self.makeServerStreamingCall(path: "/command_server.CommandServer/Run",
                                        request: request,
                                        callOptions: callOptions ?? self.defaultCallOptions,
                                        handler: handler)
  }

  /// Asynchronous unary call to Cancel.
  ///
  /// - Parameters:
  ///   - request: Request to send to Cancel.
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func cancel(_ request: CommandServer_CancelRequest, callOptions: CallOptions? = nil) -> UnaryCall<CommandServer_CancelRequest, CommandServer_CancelResponse> {
    return self.makeUnaryCall(path: "/command_server.CommandServer/Cancel",
                              request: request,
                              callOptions: callOptions ?? self.defaultCallOptions)
  }

  /// Asynchronous unary call to Ping.
  ///
  /// - Parameters:
  ///   - request: Request to send to Ping.
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func ping(_ request: CommandServer_PingRequest, callOptions: CallOptions? = nil) -> UnaryCall<CommandServer_PingRequest, CommandServer_PingResponse> {
    return self.makeUnaryCall(path: "/command_server.CommandServer/Ping",
                              request: request,
                              callOptions: callOptions ?? self.defaultCallOptions)
  }

}

/// To build a server, implement a class that conforms to this protocol.
public protocol CommandServer_CommandServerProvider: CallHandlerProvider {
  func run(request: CommandServer_RunRequest, context: StreamingResponseCallContext<CommandServer_RunResponse>) -> EventLoopFuture<GRPCStatus>
  func cancel(request: CommandServer_CancelRequest, context: StatusOnlyCallContext) -> EventLoopFuture<CommandServer_CancelResponse>
  func ping(request: CommandServer_PingRequest, context: StatusOnlyCallContext) -> EventLoopFuture<CommandServer_PingResponse>
}

extension CommandServer_CommandServerProvider {
  public var serviceName: String { return "command_server.CommandServer" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handleMethod(_ methodName: String, callHandlerContext: CallHandlerContext) -> GRPCCallHandler? {
    switch methodName {
    case "Run":
      return ServerStreamingCallHandler(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.run(request: request, context: context)
        }
      }

    case "Cancel":
      return UnaryCallHandler(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.cancel(request: request, context: context)
        }
      }

    case "Ping":
      return UnaryCallHandler(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.ping(request: request, context: context)
        }
      }

    default: return nil
    }
  }
}

