#if !canImport(ObjectiveC)
import XCTest

extension GitPluginTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GitPluginTests = [
        ("testGitBranch", testGitBranch),
        ("testGitIsDirty", testGitIsDirty),
        ("testGitIsNotDirty", testGitIsNotDirty),
        ("testGitSHA", testGitSHA),
        ("testGitUserEmailNotRedacted", testGitUserEmailNotRedacted),
        ("testGitUserEmailRedacted", testGitUserEmailRedacted),
    ]
}

extension ThermaThrottlingPluginTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ThermaThrottlingPluginTests = [
        ("testParseThermInfo100", testParseThermInfo100),
        ("testParseThermInfo25", testParseThermInfo25),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(GitPluginTests.__allTests__GitPluginTests),
        testCase(ThermaThrottlingPluginTests.__allTests__ThermaThrottlingPluginTests),
    ]
}
#endif
