apiVersion: v1
kind: Service
metadata:
  name: xcmetrics-scheduled-jobs
  labels:
    app: xcmetrics-scheduled-jobs
    tier: backend
spec:
  selector:
    app: xcmetrics-scheduled-jobs
    tier: backend
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
